source /opt/ros/humble/setup.sh
source /opt/booster/sdk_ros2/install/setup.bash

# Export dyanmic libraries and fastdds profile for booster_motion execution
export LD_LIBRARY_PATH=/app/booster_motion/lib:/app/booster_motion/lib-usr-local:/app/booster_motion/lib-x86_64-linux-gnu:$LD_LIBRARY_PATH
export FASTRTPS_DEFAULT_PROFILES_FILE=/app/booster_motion/fastdds_profile.xml

alias loco="/opt/booster/sdk/build/b1_loco_example_client 127.0.0.1"
alias looc="loco"
alias lcoo="loco"
alias mw="loco"
alias mp="loco"

alias echocmd="ros2 topic echo /booster/ros2_k2_joint_cmd"
alias echostate="ros2 topic echo /booster/ros2_k2_joint_states"
alias echolow="ros2 topic echo /low_state"

alias bmlog="cat /var/log/booster-motion.log"
alias bmerr="cat /var/log/booster-motion.err"
alias maxlog="cat /var/log/maximus.log"
alias maxerr="cat /var/log/maximus.err"
alias brilog="cat /var/log/simbridge.log"
alias brierr="cat /var/log/simbridge.err"
